
[datetime]
datetimeFormat = "2006-01-02 15:04:05" 
start = 2018-11-11T00:00:00
end = 2018-12-11T23:00:00
column = 1
  [datetime.sampling]
  num = 1
  unit = "min"


[data]
min = 0.0
max = 0.001
pointtype = "float"

  [[data.datetime]]
  column = 7
  datetimeFormat = "15:04:05"
  add = 2000 # ms

  [[data.tag]]
  column = 4
  value = ["x", "y"]

  [[data.tag]]
  column = 5
  value = ["a", "b", "c"]

  [[data.tag]]
  column = 6
  value = ["XX", "YY"]

  [[data.abnormal]]
  column = 2
  min = 100.0
  max = 200.0
  pointtype = "int"
  start = 2018-11-12T00:00:00
  end = 2018-11-12T23:00:00

    [data.abnormal.transition]
    num = 1
    unit = "hour"

  [[data.abnormal]]
  column = 3
  min = 20.0
  max = 30.0
  pointtype = "float"
  start = 2018-11-11T00:00:00
  end = 2018-11-11T10:00:00

    [data.abnormal.transition]
    num = 5
    unit = "min"

[[header]]
row = ["datetime", "aaaa", "bbbb", "cccc", "dddd", "eeee", "ffff", "gggg"]

[[header]]
row = ["timestamp", "number", "number", "number", "string", "string", "string", "string"]
